name: PR
on:
  pull_request:
    branches:
      - master
jobs:
  test-build:
    runs-on: ubuntu-latest
    if: |
      ! contains(github.event.head_commit.message, '[skip ci]')
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup rust
        uses: hecrj/setup-rust-action@v1.4.1
        with:
          rust-version: stable
          components: clippy
          targets: wasm32-unknown-unknown
      - uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"
      - name: lint
        run: |
          cargo clippy
      - name: build-image
        run: |
          ./scripts/build.sh prod
